version: '3.9'

services:
  mfe-orquestrador:
    image: nginx:stable-alpine
    working_dir: /usr/share/nginx/html/
    volumes:
      - /srv/docker/volumes/orquestrador/dist:/usr/share/nginx/html
      - /srv/docker/volumes/orquestrador/nginx/default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
        - "traefik.http.routers.frontend.entrypoints=web"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 30s
    networks:
      - traefik-net




networks:
  traefik-net:
    external: true
